##########################################################################################################
############################################# 关于actuator配置 ############################################
##########################################################################################################
management:
  endpoints:
    web:
      exposure:
        include: 'loggers'